spring:
  application:
    name: adminapplication

server:
  port: 8770



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  security:
    enabled: false

security:
  basic:
    enabled: true
  user:
    name: test
    password: test